name: Seda EPG Bot

on:
  schedule:
    - cron: '0 */8 * * *'  # Her 8 saatte bir (UTC)
  workflow_dispatch:

jobs:
  run-epg-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Değişiklikleri push edebilmek için gerekli

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run seda.py
        run: python seda.py

      - name: Commit and push changes
        run: |
          git config --global user.name "Kablo EPG Bot"
          git config --global user.email "epg-bot@users.noreply.github.com"
          git pull --rebase origin main || true
          git add sedaepg.xml
          git commit -m "Güncel EPG XML [bot]" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
